### ISSUE TITLE
几个个问题请教

### ISSUE THREAD

**Issue by z0ffy** [wanwu/cheetah-capture#5]
感谢大佬，在使用中发现以下几个个问题，还请解疑答惑，感觉

1、info传1的话会报错  [Log] RuntimeError: Division by zero (evaluating '(_captureByCount = Module["_captureByCount"] = Module["asm"]["captureByCount"]).apply(null, arguments)')

2、info传2的话，截取收尾各一张

3、上传23s视频截取10张，按照2s间隔截取的话发现结果中存在近似图（可能时间间隔问题）

4、onChange发现触发超过十次，同一毫秒打印多次

**Comment by hixuanxuan** [comment]
哈喽~
1. 测试v0.1.5的版本产物跑demo info穿1无问题，是否是自编译产物有问题呢，相同环境下可以排查下。
2. 目前的关键帧优先策略 如果关键帧数目 > 2，info传2确实是取最后一张，算的是相同间隔。
3. 近似图片可能因为你的视频关键帧相似，或者时间很短关键帧不够，会优先取出来全部关键帧再进行相等时间间隔非关键帧补齐。
4. onChange是抽出来一张就会触发一次渲染，因此你传>10的info确实会超过10次。
有问题欢迎提问探讨~~

**Comment by z0ffy** [comment]
好的，感谢🙏
