### ISSUE TITLE
视频末尾的关键帧丢失

### ISSUE THREAD

**Issue by Kuohao-wu** [wanwu/cheetah-capture#6]
请问一下作者，是什么原因导致视频后面几秒的帧会丢失，是因为按照张数分割导致最后几秒未达到分割的偏移量导致不再抽帧的缘故吗？试了好3-4分钟不等的视频，都是这样，视频比较短的话，张数比较多的情况下就比较正常

如果我按张数为2去生成，第一张是视频首帧，第二张是视频最后几秒的那帧。

运行环境：win11
emsdk安装正常，编译wasm也正常。

**Comment by hixuanxuan** [comment]
哈喽～目前的抽帧策略是 第一张封面图一定是关键帧，剩下会按照总体的关键帧数计算相等间隔去选择，如果原视频关键帧较多并且分布不均，是可能出现偏移量看起来比较大的情况，建议业务侧选择抽取8张以上的图，可以对大部分视频都有较好的间隔效果。

**Comment by Kuohao-wu** [comment]
好的，了解。问题其实不算太大。还有一个问题就是能不能获取到当前截帧对应的视频播放时间，有场景需要在对应的帧图片上显示当前帧对应的时间，我看api只有duration一个总时长。

**Comment by hixuanxuan** [comment]
时间确实可以取到但目前还没有暴露，后续会增加这个属性的支持吧~~
