### ISSUE TITLE
每次截图都会报错，能帮忙分析下这个错误有影响吗

### ISSUE THREAD

**Issue by colinyao** [wanwu/cheetah-capture#7]
![image](https://github.com/wanwu/cheetah-capture/assets/14851287/e7cd6787-9d55-49a8-9fdc-857f3432c9ce)

**Comment by newives** [comment]
这个警告 来自 https://github.com/wanwu/cheetah-capture/tree/main/lib/ffmpeg-emcc
lib/ffmpeg-emcc文件目前这个仓库并不能友好的编译成功，打包出来的都有问题

**Comment by hixuanxuan** [comment]
哈喽～这是个警告不是报错哈，对你的输出结果没有影响，意思是FFmpeg没有找到从YUV420p到RGB24的加速色彩空间转换，可能是因为你的设备硬件或驱动程序不支持这种转换～
